language: r
sudo: false
cache: packages

r_github_packages:
  - hadley/devtools

r:
 - release
 - devel
 - oldrel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
