language: r
sudo: false
cache: packages

before_install: Rscript -e 'source("https://install-github.me/hadley/devtools")'

r:
 - 3.1.3
 - release
 - devel
 - oldrel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
